### ISSUE TITLE
Additional includes in standard library?

### ISSUE THREAD

**Issue by cmpute** [b1f6c1c4/cpp-create-objects#1]
like `#include <memory>`

**Comment by b1f6c1c4** [comment]
Absolutely allowed. 
* If it's very commonly used (like `stdlib.h`), add to `header.hpp`
* If not, add to your `.hpp` file(s).

**Comment by cmpute** [comment]
Sure, and the non-standard headers are obviously not allowed imo, right?

**Comment by b1f6c1c4** [comment]
I don't understand why you need extra headers just to create objects.

If you want to use boost, you can fork this project and change the rule.

**Comment by cmpute** [comment]
#2 That's why I mentioned it.
